import Head from 'next/head'
import Footer from '../components/Footer/Footer'
import Hero from '../components/Hero/Hero'
import JoinPage from '../components/Join/Join'
import Plans from '../components/Plans/Plans'
import Programs from '../components/Programs/Programs'
import Reasons from '../components/Reasons/Reasons'
import Testimonials from '../components/Testimonials/Testimonials'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>The Fit Club</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <Hero/>
        <Programs/>
        <Reasons/>
        <Plans/>
        <Testimonials/>
        <JoinPage/>
        <Footer/>
      </main>
    </div>
  )
}
