import Head from 'next/head'
import Footer from '../components/Footer/Footer'
import Hero from '../components/Hero/Hero'
import JoinPage from '../components/Join/Join'
import Plans from '../components/Plans/Plans'
import Programs from '../components/Programs/Programs'
import Reasons from '../components/Reasons/Reasons'
import Testimonials from '../components/Testimonials/Testimonials'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>The Fit Club</title>
        <meta name="description" content="Generated by create next app" />
        {/* Favicon */}
        <link rel="apple-touch-icon" sizes="180x180" href="../favicon_io/apple-touch-icon.png"/>
        <link rel="icon" type="image/png" sizes="32x32" href="../favicon_io/favicon-32x32.png"/>
        <link rel="icon" type="image/png" sizes="16x16" href="../favicon_io/favicon-16x16.png"/>
        <link rel="manifest" href="../favicon_io/site.webmanifest"/>
        {/* Fonts */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main className={styles.main}>
        <Hero/>
        <Programs/>
        <Reasons/>
        <Plans/>
        <Testimonials/>
        <JoinPage/>
        <Footer/>
      </main>
    </div>
  )
}
